#!/usr/bin/env bash
# This script configures DNS for localhost and facebook.com

# Adding localhost resolution
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null

# Adding Facebook.com resolution
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
