#!/bin/bash
find . -maxdepth 1 -type f -name *.html -exec bash -c '[[ ! -e ../ ]] || [[  -gt 1675877297 ]] && cp  ../' -- {} \;
find . -maxdepth 1 -type f -name *.html -exec bash -c '[[ ! -e ../ ]] || [[  -gt 1675877297 ]] && cp  ../' -- {} \;
cp '' ../''
