#!/usr/bin/env bash
# This script manages 'manage_my_process'

if [ -f /etc/default/rcS ]; then
	. /etc/default/rcS
fi

if [ -f /lib/lsb/init-functions ]; then
	. /lib/lsb/init-functions
fi

MANAGE_MY_PROCESS_SCRIPT="./manage_my_process"

start() {
	echo "Starting manage_my_process..."
	$MANAGE_MY_PROCESS_SCRIPT start
}

# Function to stop the manage_my_process script
stop() {
	echo "Stopping manage_my_process..."
	$MANAGE_MY_PROCESS_SCRIPT stop
}

# Function to restart the manage_my_process script
restart() {
	echo "Restarting manage_my_process..."
	$MANAGE_MY_PROCESS_SCRIPT restart
}

# Main logic to handle command line arguments
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
        	;;
	*)
        	echo "Usage: $0 {start|stop|restart}"
        	exit 1
        	;;
esac

exit 0
