#!/usr/bin/env bash
# This script displays simply the bash and pid

for pid_dir in /proc/[0-9]*; do
	pid=$(basename "$pid_dir")

	if [[ -r "$pid_dir/cmdline" ]]; then
		process_name=$(tr -d '\0' < "$pid_dir/cmdline")
		if [[ "$process_name" == *bash* ]]; then
			echo "$pid $process_name"
		fi
	fi	
done
