#!/usr/bin/env bash
# This script sends a termination signal to stop the process infinity and beyond

pid=$(pgrep -f "4-to_infinity_and_beyond")
if [ -n "$pid" ]; then
    kill -s SIGTERM "$pid"
else
    echo "Process not found"
fi
