#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely and prints a string.

sigterm_handler() {
	echo "I am invincible!!!"
	exit 0
}

trap 'sigterm_handler' SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
