#!/usr/bin/env bash
# Bash script to manage a background process

if [[ $# -ne 1 ]]; then
	echo "Usage: $0 {start|stop|restart}"
	exit 1
fi

start_process() {
	./manage_my_process &
	
	pid=$!
	
	echo "$pid" > /var/run/my_process.pid
	
	echo "manage_my_process started"
}

stop_process() {
	if [[ -f /var/run/my_process.pid ]]; then
		pid=$(cat /var/run/my_process.pid)
	
		kill "$pid"
		rm -f /var/run/my_process.pid
	
		echo "manage_my_process stopped"
	else
		echo "PID not found. manage_my_process may not be running."
	fi
}

restart_process() {
	stop_process
	start_process
	echo "manage_my_process restarted"
}

# Main Logic

case "$1" in
	start)
		start_process
		;;
	stop)
		stop_process
		;;
	restart)
		restart_process
		;;
	*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac

exit 0
