#!/usr/bin/env bash
# This script parses Apache log files and displays visitor IP

log_file="apache-access.log"
if [ ! -f "$log_file" ]; then
	echo "Error: $log_file does not exist."
	exit 1
fi

awk '{print $1, $9}' "$log_file"
