#!/usr/bin/env bash
# This script displays content of the current working directory

for file in *; do
	if [ ! -h "$file" ] && [ ! -d "$file" ]; then
		name=$(echo "$file" | cut -d '-' -f 2-)
		echo "$name"
	fi
done
